// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var View$ReactTemplate = require("./view.bs.js");

var context = View$ReactTemplate.init(/* () */0);

var world = /* record */[
  /* t */1000,
  /* dt */100,
  /* trex : record */[
    /* state */"running",
    /* size : record */[
      /* width */44,
      /* height */47
    ],
    /* imgPos : record */[
      /* x */890,
      /* y */2
    ],
    /* duckingSize : record */[
      /* width */59,
      /* height */32
    ],
    /* duckingImgPos : record */[
      /* x */1112,
      /* y */19
    ]
  ]
];

function tick() {
  return View$ReactTemplate.render(context, world);
}

View$ReactTemplate.render(context, world);

setInterval(tick, 20);

exports.context = context;
exports.world   = world;
exports.tick    = tick;
/* context Not a pure module */
